apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Set the namespace for all resources using a placeholder.
namespace: ${NAMESPACE}

# Use a prefix for all object names. You can substitute the PROJECT_NAME variable.
namePrefix: ${PROJECT_NAME}-

# List all the resources (manifests) you want to deploy.
resources:
- common/statefulset.yaml
- common/service.yaml
- openshift/route.yaml
- rbac/exec-rbac-role.yaml
- rbac/exec-rbac-rolebinding.yaml

# Generate the ConfigMap with a variable name.
configMapGenerator:
- name: config
  options:
    disableNameSuffixHash: true

# Include patches to update the Service, StatefulSet, Route, and RBAC resources.

# Define the image to be updated.
# images:
# - name: ghcr.io/llm-d/placeholder
#   newName: ghcr.io/llm-d/${IMAGE_TAG_BASE}
#   newTag: ${VERSION}
patches:
- path: common/patch-service.yaml
- path: common/patch-statefulset.yaml
- path: openshift/patch-route.yaml
- path: rbac/patch-rbac-role.yaml
- path: rbac/patch-rbac-rolebinding.yaml
